In [1]:
import pandas as pd
import numpy as np

In [3]:
#Data loading:
Phenotypes = pd.read_csv(r"C:\Users\Ella Katz\Desktop\Post-doc\Personal\Springboard\git_hub_projects\Springboard_data\Second_capstone\Datasets\All_Data_emmeans_info_V1.csv")
Classifications = pd.read_csv(r"C:\Users\Ella Katz\Desktop\Post-doc\Personal\Springboard\git_hub_projects\Springboard_data\Second_capstone\Datasets\Seeds_classification.csv")
Environmental_data = pd.read_csv(r"C:\Users\Ella Katz\Desktop\Post-doc\Personal\Springboard\git_hub_projects\Springboard_data\Second_capstone\Datasets\Environmental_data.csv")

In [8]:
print(Phenotypes.shape)
print(Classifications.shape)
print(Environmental_data.shape)

(3888, 48)
(797, 2)
(1131, 212)

In [9]:
#Data joining:
Data_1 = pd.merge(Phenotypes, Classifications, how="left", on="CS_number")

print(Phenotypes.shape)
print(Classifications.shape)
print(Data_1.shape)

(3888, 48)
(797, 2)
(3888, 49)

In [12]:
Data_1.dtypes

CS_number                object
name                     object
country                  object
latitude                float64
longitude               float64
collector                object
seq_by                   object
Experiment               object
N_source                 object
N_concentration         float64
N_treatment              object
Leaf_Area               float64
Total_roots             float64
PR_length               float64
Number_of_LR            float64
Total_LR                float64
LR_density              float64
LR_length               float64
LR_to_total_roots       float64
LR_to_PR                float64
X2MSO                   float64
X3OHP                   float64
X4OHB                   float64
X3MSO                   float64
OH_3_Butenyl            float64
X4MSO                   float64
Allyl                   float64
X5MSO                   float64
Branches                float64
X3_Butenyl              float64
X6MSO                   float64
X3MT                    float64
X7MSO                   float64
X4_Pentenyl             float64
X4MT                    float64
X8MSO                   float64
I3M                     float64
X4MOI3M                 float64
Aliphatic               float64
Indolic                 float64
C3                      float64
C4                      float64
C3_ratio                float64
Alk                     float64
GSOH                    float64
SC                      float64
LC                      float64
Total_GSL               float64
Seeds_classification     object
dtype: object

In [18]:
Data_1['Seeds_classification'].nunique()

7

In [25]:
#Creating dummies from Seeds_classification:
Data_2 = pd.get_dummies(Data_1, prefix='Chemotype_', columns=['Seeds_classification'])
Data_3 = pd.get_dummies(Data_2, prefix='Treatment_', columns=['N_treatment'])
Data_3.head()

,CS_number,name,country,latitude,longitude,collector,seq_by,Experiment,N_source,N_concentration,...,Chemotype__3OHP,Chemotype__4MSO,Chemotype__4OHB,Chemotype__Allyl,Chemotype__Butenyl,Chemotype__OH-But,Treatment__KNO3_0.1,Treatment__KNO3_1,Treatment__NH4HCO3_0.1,Treatment__NH4HCO3_1
0,CS76347,Aitba-2,MAR,31.4800,0.000,0,MPI,C,NH4HCO3,0.1,...,0,0,0,0,0,0,0,0,1,0
1,CS76347,Aitba-2,MAR,31.4800,0.000,0,MPI,C,NH4HCO3,1.0,...,0,0,0,0,0,0,0,0,0,1
2,CS76347,Aitba-2,MAR,31.4800,0.000,0,MPI,C,KNO3,0.1,...,0,0,0,0,0,0,1,0,0,0
3,CS76347,Aitba-2,MAR,31.4800,0.000,0,MPI,C,KNO3,1.0,...,0,0,0,0,0,0,0,1,0,0
4,CS76350,Vezzano-2.2,ITA,46.6297,10.817,Joerg Wunder,MPI,C,KNO3,1.0,...,0,0,0,1,0,0,0,1,0,0

In [56]:
#Scale standardization
from sklearn import preprocessing

min_max_scaler = preprocessing.MinMaxScaler()
Scaled = min_max_scaler.fit_transform(Data_3[['Leaf_Area', 'PR_length', 'Number_of_LR', 'Total_LR', 'Total_GSL']])
Data_4 = pd.DataFrame(Scaled)
print(Data_4.describe())
print(Data_4.shape)

                 0            1            2            3            4
count  3883.000000  3888.000000  3888.000000  3888.000000  3888.000000
mean      0.132390     0.347455     0.118590     0.088303     0.016398
std       0.102808     0.154002     0.147541     0.137990     0.032955
min       0.000000     0.000000     0.000000     0.000000     0.000000
25%       0.069057     0.235247     0.010417     0.000629     0.001258
50%       0.101543     0.347329     0.062500     0.029062     0.007237
75%       0.163051     0.455077     0.171875     0.114802     0.018959
max       1.000000     1.000000     1.000000     1.000000     1.000000
(3888, 5)

In [63]:
#Orgnizing and combining with the rest of the data:
Data_4.columns = ['Leaf_Area', 'PR_length', 'Number_of_LR', 'Total_LR',  'Total_GSL']
Data_4.head()

   Leaf_Area  PR_length  Number_of_LR      Total_LR  Total_GSL
0   0.089649   0.343251  1.406250e-01  3.327818e-02   0.036974
1   0.142597   0.391831  2.604167e-01  1.098052e-01   0.114480
2   0.092834   0.246517  3.187500e-13  0.000000e+00   0.011617
3   0.119048   0.378752  1.250000e-01  3.633881e-02   0.012177
4   0.063116   0.247669  2.362500e-13  5.365835e-13   0.014358

In [64]:
Data_3.drop(['Leaf_Area', 'PR_length', 'Number_of_LR', 'Total_LR',  'Total_GSL'], axis=1, inplace=True)
Data_3.head()

,CS_number,name,country,latitude,longitude,collector,seq_by,Experiment,N_source,N_concentration,...,Chemotype__3OHP,Chemotype__4MSO,Chemotype__4OHB,Chemotype__Allyl,Chemotype__Butenyl,Chemotype__OH-But,Treatment__KNO3_0.1,Treatment__KNO3_1,Treatment__NH4HCO3_0.1,Treatment__NH4HCO3_1
0,CS76347,Aitba-2,MAR,31.4800,0.000,0,MPI,C,NH4HCO3,0.1,...,0,0,0,0,0,0,0,0,1,0
1,CS76347,Aitba-2,MAR,31.4800,0.000,0,MPI,C,NH4HCO3,1.0,...,0,0,0,0,0,0,0,0,0,1
2,CS76347,Aitba-2,MAR,31.4800,0.000,0,MPI,C,KNO3,0.1,...,0,0,0,0,0,0,1,0,0,0
3,CS76347,Aitba-2,MAR,31.4800,0.000,0,MPI,C,KNO3,1.0,...,0,0,0,0,0,0,0,1,0,0
4,CS76350,Vezzano-2.2,ITA,46.6297,10.817,Joerg Wunder,MPI,C,KNO3,1.0,...,0,0,0,1,0,0,0,1,0,0

In [72]:
Data_5 = pd.concat([Data_3, Data_4], axis=1)
Data_5.shape

(3888, 58)

In [74]:
#Spliting the data:
from sklearn.model_selection import train_test_split

train, test = train_test_split(Data_5, test_size=0.2)
print(train.shape)
print(test.shape)

(3110, 58)
(778, 58)